name: New Skill Request
description: Submit a new skill for the marketplace. No coding required — just describe what you want Claude to do.
labels: ["new-skill"]
body:
  - type: input
    id: skill-name
    attributes:
      label: Skill Name
      description: A short kebab-case name for the skill (e.g., "summarize-doc", "draft-email").
      placeholder: my-skill-name
    validations:
      required: true

  - type: dropdown
    id: department
    attributes:
      label: Department
      description: Which department plugin should this skill belong to?
      options:
        - shared
        - engineering
        - marketing
        - research
        - sales
        - customer-success
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: Short Description
      description: A one-line description of what this skill does (used in frontmatter).
      placeholder: "Summarize a document and extract key takeaways"
    validations:
      required: true

  - type: textarea
    id: instructions
    attributes:
      label: Instructions
      description: Step-by-step instructions for Claude to follow when this skill is invoked. Be specific about what Claude should do, what tools to use, and what output to produce.
      placeholder: |
        1. Read the document provided by the user
        2. Identify the key themes and arguments
        3. Write a 3-paragraph summary
        4. List 5 key takeaways as bullet points
    validations:
      required: true

  - type: textarea
    id: safety-rules
    attributes:
      label: Safety Rules
      description: Optional constraints or guardrails (e.g., "never delete files", "always ask before overwriting").
      placeholder: |
        - Never modify the original document
        - Ask for confirmation before writing output files
    validations:
      required: false
